import { useState } from "react";
import { getConfirmations, type ConfirmationRecord } from "../../api/erp";
import DataTable, { type Column } from "../../components/DataTable";
import { useERPType } from "../../hooks/useERPType";

function docNumber(r: ConfirmationRecord): string {
  return r.sap_document ?? r.erp_document ?? "\u2014";
}

function payload(r: ConfirmationRecord): Record<string, unknown> | undefined {
  return r.sap_payload ?? r.erp_payload;
}

const columns: Column<ConfirmationRecord>[] = [
  { key: "type", header: "Type", render: (r) => <span className="px-2 py-0.5 rounded text-xs font-medium bg-blue-100 text-blue-800">{r.type}</span> },
  { key: "erp_document", header: "Doc #", render: (r) => docNumber(r) },
  { key: "order_id", header: "Order" },
  { key: "posted_at", header: "Posted At", render: (r) => new Date(r.posted_at).toLocaleString() },
  {
    key: "erp_payload",
    header: "Payload",
    render: (r) => (
      <pre className="text-xs max-w-md overflow-auto whitespace-pre-wrap">
        {JSON.stringify(payload(r), null, 2)}
      </pre>
    ),
  },
];

export default function ERPConfirmationsPage() {
  const [records, setRecords] = useState<ConfirmationRecord[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [loaded, setLoaded] = useState(false);
  const { erpLabel } = useERPType();

  const handleFetch = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await getConfirmations();
      setRecords(data);
      setLoaded(true);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Fetch failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-4">
      <p className="text-sm text-gray-600">View all {erpLabel} confirmation documents generated by outbound reports.</p>
      <button onClick={handleFetch} disabled={loading} className="px-4 py-2 bg-blue-600 text-white text-sm rounded hover:bg-blue-700 disabled:opacity-50">
        {loading ? "Loading\u2026" : "Refresh Confirmations"}
      </button>
      {error && <div className="p-3 bg-red-50 border border-red-200 text-red-700 rounded text-sm">{error}</div>}
      {loaded && records.length === 0 && <div className="p-3 bg-gray-50 border text-gray-600 rounded text-sm">No confirmations yet. Submit outbound reports to generate them.</div>}
      {records.length > 0 && (
        <>
          <div className="text-sm text-gray-600">{records.length} confirmation(s)</div>
          <DataTable data={records} columns={columns} />
        </>
      )}
    </div>
  );
}
