"""add_equipment_state_models_table_and_equipment_state_model_id

Revision ID: 8c7e3fa160fd
Revises: ba6f6fcc58bb
Create Date: 2026-03-29 10:49:54.775978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7e3fa160fd'
down_revision: Union[str, None] = 'ba6f6fcc58bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_state_models',
    sa.Column('model_id', sa.String(length=50), nullable=False, comment="Plugin identifier, e.g. 'packml', 'semi_e10'"),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Human-friendly name, e.g. 'PackML (ISA-TR88)'"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('initial_state', sa.String(length=50), nullable=False, comment='Name of the initial/default state'),
    sa.Column('states', sa.JSON(), nullable=False, comment='Array of state definitions with canonical mappings'),
    sa.Column('transitions', sa.JSON(), nullable=False, comment='Array of valid state transitions'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_state_models_id'), 'equipment_state_models', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_state_models_model_id'), 'equipment_state_models', ['model_id'], unique=True)
    op.add_column('equipment', sa.Column('state_model_id', sa.String(length=50), nullable=True, comment="State machine model ID (e.g. 'packml', 'semi_e10'). Null = 100% available."))
    op.create_index(op.f('ix_equipment_state_model_id'), 'equipment', ['state_model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_state_model_id'), table_name='equipment')
    op.drop_column('equipment', 'state_model_id')
    op.drop_index(op.f('ix_equipment_state_models_model_id'), table_name='equipment_state_models')
    op.drop_index(op.f('ix_equipment_state_models_id'), table_name='equipment_state_models')
    op.drop_table('equipment_state_models')
    # ### end Alembic commands ###
