"""drop process_segment_dependencies; add input/output disposition lists and is_initial_step

Revision ID: 5aefea3fbea4
Revises: d8a5f0e9c31b
Create Date: 2026-04-30 18:05:04.873275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5aefea3fbea4'
down_revision: Union[str, None] = 'd8a5f0e9c31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _dialect() -> str:
    return op.get_bind().dialect.name


def _drop_fk_by_column(table: str, column: str) -> None:
    """Drop an unnamed FK constraint on MySQL using INFORMATION_SCHEMA lookup."""
    result = op.get_bind().execute(sa.text(
        "SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :t "
        "AND COLUMN_NAME = :c AND REFERENCED_TABLE_NAME IS NOT NULL"
    ), {"t": table, "c": column})
    row = result.fetchone()
    if row:
        op.drop_constraint(row[0], table, type_="foreignkey")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_segment_input_dispositions',
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('disposition_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, comment="Sort order within the step's input list (UI hint only)"),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('created_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was created (UTC)'),
    sa.Column('updated_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was last updated (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['disposition_id'], ['dispositions.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['process_segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id', 'disposition_id', name='uq_psid_step_disp')
    )
    op.create_index(op.f('ix_process_segment_input_dispositions_disposition_id'), 'process_segment_input_dispositions', ['disposition_id'], unique=False)
    op.create_index(op.f('ix_process_segment_input_dispositions_id'), 'process_segment_input_dispositions', ['id'], unique=False)
    op.create_index(op.f('ix_process_segment_input_dispositions_step_id'), 'process_segment_input_dispositions', ['step_id'], unique=False)
    op.create_table('process_segment_output_dispositions',
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('disposition_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, comment="Sort order within the step's output list (UI hint only)"),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('created_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was created (UTC)'),
    sa.Column('updated_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was last updated (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['disposition_id'], ['dispositions.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['process_segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id', 'disposition_id', name='uq_psod_step_disp')
    )
    op.create_index(op.f('ix_process_segment_output_dispositions_disposition_id'), 'process_segment_output_dispositions', ['disposition_id'], unique=False)
    op.create_index(op.f('ix_process_segment_output_dispositions_id'), 'process_segment_output_dispositions', ['id'], unique=False)
    op.create_index(op.f('ix_process_segment_output_dispositions_step_id'), 'process_segment_output_dispositions', ['step_id'], unique=False)
    # plugin_file_drop_results is created by a runtime plugin, not Alembic;
    # only drop it if it actually exists in this environment.
    bind = op.get_bind()
    if sa.inspect(bind).has_table('plugin_file_drop_results'):
        op.drop_table('plugin_file_drop_results')
    if _dialect() == "mysql":
        # MySQL: FK constraints must be dropped before the indexes they protect
        op.drop_constraint("process_segment_dependencies_disposition_id_fkey",
                           "process_segment_dependencies", type_="foreignkey")
        _drop_fk_by_column("process_segment_dependencies", "from_step_id")
        _drop_fk_by_column("process_segment_dependencies", "to_step_id")
    op.drop_index(op.f('ix_process_segment_dependencies_disposition_id'), table_name='process_segment_dependencies')
    op.drop_index(op.f('ix_process_segment_dependencies_from_step_id'), table_name='process_segment_dependencies')
    op.drop_index(op.f('ix_process_segment_dependencies_id'), table_name='process_segment_dependencies')
    op.drop_index(op.f('ix_process_segment_dependencies_to_step_id'), table_name='process_segment_dependencies')
    op.drop_table('process_segment_dependencies')
    if _dialect() != "mysql":  # MySQL: sa.UUID() invalid; these alter comment only
        op.alter_column('equipment_class_properties', 'uom_id',
                   existing_type=sa.UUID(),
                   comment='Unit of measure for this property (nullable for dimensionless values)',
                   existing_nullable=True)
    op.add_column('process_segments', sa.Column('is_initial_step', sa.Boolean(), nullable=False, comment="Marks this step as the route's entry point. Exactly one step per route should be flagged. Used by RoutingEngineService to resolve the first step for a new lot/unit. The empty-input rule is a UX hint; this flag is authoritative."))
    if _dialect() == "mysql":
        # MySQL: drop FK before its index
        _drop_fk_by_column("process_segments", "disposition_id")
    op.drop_index(op.f('ix_process_segments_disposition_id'), table_name='process_segments')
    if _dialect() != "mysql":
        op.drop_constraint(op.f('process_segments_disposition_id_fkey'), 'process_segments', type_='foreignkey')
    op.drop_column('process_segments', 'disposition_id')
    if _dialect() != "mysql":  # MySQL: sa.UUID() invalid; these alter comment only
        op.alter_column('segment_equipment_requirements', 'equipment_class_id',
                   existing_type=sa.UUID(),
                   comment='Equipment class required at this step (mutually exclusive with equipment_id)',
                   existing_nullable=True)
        op.alter_column('segment_equipment_requirements', 'equipment_id',
                   existing_type=sa.UUID(),
                   comment='Specific equipment instance required at this step (mutually exclusive with equipment_class_id)',
                   existing_comment='Specific equipment instance required at this step',
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('segment_equipment_requirements', 'equipment_id',
               existing_type=sa.UUID(),
               comment='Specific equipment instance required at this step',
               existing_comment='Specific equipment instance required at this step (mutually exclusive with equipment_class_id)',
               existing_nullable=True)
    op.alter_column('segment_equipment_requirements', 'equipment_class_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Equipment class required at this step (mutually exclusive with equipment_id)',
               existing_nullable=True)
    op.add_column('process_segments', sa.Column('disposition_id', sa.UUID(), autoincrement=False, nullable=True, comment='FK to the disposition that routes WIP to this step'))
    op.create_foreign_key(op.f('process_segments_disposition_id_fkey'), 'process_segments', 'dispositions', ['disposition_id'], ['id'])
    op.create_index(op.f('ix_process_segments_disposition_id'), 'process_segments', ['disposition_id'], unique=False)
    op.drop_column('process_segments', 'is_initial_step')
    op.alter_column('equipment_class_properties', 'uom_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unit of measure for this property (nullable for dimensionless values)',
               existing_nullable=True)
    op.create_table('process_segment_dependencies',
    sa.Column('from_step_id', sa.UUID(), autoincrement=False, nullable=False, comment='Source step this transition originates from'),
    sa.Column('to_step_id', sa.UUID(), autoincrement=False, nullable=False, comment='Target step this transition leads to'),
    sa.Column('condition', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment="Condition: 'always', 'on_pass', 'on_fail', 'on_rework', 'disposition'"),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Default transition when multiple match. Exactly one per from_step should be default.'),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False, comment='Higher priority transitions are evaluated first (0 = lowest)'),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment="Human-readable label for disposition choices (e.g. 'Return to rework', 'Scrap')"),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('created_at_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Timestamp when the entity was created (UTC)'),
    sa.Column('updated_at_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Timestamp when the entity was last updated (UTC)'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.Column('disposition_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['disposition_id'], ['dispositions.id'], name=op.f('process_segment_dependencies_disposition_id_fkey')),
    sa.ForeignKeyConstraint(['from_step_id'], ['process_segments.id'], name=op.f('process_segment_dependencies_from_step_id_fkey')),
    sa.ForeignKeyConstraint(['to_step_id'], ['process_segments.id'], name=op.f('process_segment_dependencies_to_step_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('process_segment_dependencies_pkey'))
    )
    op.create_index(op.f('ix_process_segment_dependencies_to_step_id'), 'process_segment_dependencies', ['to_step_id'], unique=False)
    op.create_index(op.f('ix_process_segment_dependencies_id'), 'process_segment_dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_process_segment_dependencies_from_step_id'), 'process_segment_dependencies', ['from_step_id'], unique=False)
    op.create_index(op.f('ix_process_segment_dependencies_disposition_id'), 'process_segment_dependencies', ['disposition_id'], unique=False)
    op.create_table('plugin_file_drop_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('test_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('equipment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('serial', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lot', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(length=20), server_default=sa.text("'pass'::character varying"), autoincrement=False, nullable=False),
    sa.Column('measurements', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('source_file', sa.VARCHAR(length=500), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('tested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tested_at_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at_utc', postgresql.TIMESTAMP(), server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('plugin_file_drop_results_pkey'))
    )
    op.drop_index(op.f('ix_process_segment_output_dispositions_step_id'), table_name='process_segment_output_dispositions')
    op.drop_index(op.f('ix_process_segment_output_dispositions_id'), table_name='process_segment_output_dispositions')
    op.drop_index(op.f('ix_process_segment_output_dispositions_disposition_id'), table_name='process_segment_output_dispositions')
    op.drop_table('process_segment_output_dispositions')
    op.drop_index(op.f('ix_process_segment_input_dispositions_step_id'), table_name='process_segment_input_dispositions')
    op.drop_index(op.f('ix_process_segment_input_dispositions_id'), table_name='process_segment_input_dispositions')
    op.drop_index(op.f('ix_process_segment_input_dispositions_disposition_id'), table_name='process_segment_input_dispositions')
    op.drop_table('process_segment_input_dispositions')
    # ### end Alembic commands ###
