"""add_rate_uom_numerator_denominator_fks

Revision ID: 93090f15e87b
Revises: d4e5f6a7b8c9
Create Date: 2026-03-27 11:35:03.117395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93090f15e87b'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bom_items', 'uom',
               existing_type=sa.VARCHAR(length=20),
               comment='Unit of measure — FK to units_of_measure.symbol',
               existing_nullable=False)
    op.alter_column('data_definitions', 'uom',
               existing_type=sa.VARCHAR(length=20),
               comment='Unit of measure — FK to units_of_measure.symbol',
               existing_comment='Unit of measure for numeric values (e.g. °C, Nm, mm)',
               existing_nullable=True)
    op.alter_column('material_definitions', 'material_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Material type: raw, intermediate, finished, semi, consumable, packaging, spare',
               existing_comment='Material type: raw, intermediate, finished',
               existing_nullable=False)
    op.alter_column('material_definitions', 'uom',
               existing_type=sa.VARCHAR(length=20),
               comment='Default unit of measure — FK to units_of_measure.symbol',
               existing_comment='Default unit of measure (e.g. EA, kg, L)',
               existing_nullable=False)
    op.alter_column('plugin_config', 'config_overrides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional runtime config overrides (merged over manifest defaults)',
               existing_comment='User-overridden config values (merged over manifest defaults)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('plugin_config', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the entity',
               existing_nullable=False)
    op.alter_column('plugin_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the entity was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plugin_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the entity was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plugin_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag. False means the entity is logically deleted.',
               existing_comment='Soft delete flag',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_plugin_config_id'), 'plugin_config', ['id'], unique=False)
    op.alter_column('product_definitions', 'uom',
               existing_type=sa.VARCHAR(length=20),
               comment='Unit of measure — FK to units_of_measure.symbol',
               existing_comment='Unit of measure (EA, KG, L, etc.)',
               existing_nullable=False)
    op.alter_column('step_parameters', 'uom',
               existing_type=sa.VARCHAR(length=20),
               comment='Unit of measure — FK to units_of_measure.symbol',
               existing_nullable=True)
    op.add_column('units_of_measure', sa.Column('numerator_uom_id', sa.UUID(), nullable=True, comment='For rate UoMs: the numerator unit (e.g. EA in EA/h)'))
    op.add_column('units_of_measure', sa.Column('denominator_uom_id', sa.UUID(), nullable=True, comment='For rate UoMs: the denominator unit (e.g. h in EA/h)'))
    op.alter_column('units_of_measure', 'uom_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Dimension type: mass, time, length, temperature, volume, count, rate, …',
               existing_comment='Dimension type: mass, time, length, temperature, volume, count, …',
               existing_nullable=False)
    op.create_foreign_key(None, 'units_of_measure', 'units_of_measure', ['numerator_uom_id'], ['id'])
    op.create_foreign_key(None, 'units_of_measure', 'units_of_measure', ['denominator_uom_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units_of_measure', type_='foreignkey')
    op.drop_constraint(None, 'units_of_measure', type_='foreignkey')
    op.alter_column('units_of_measure', 'uom_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Dimension type: mass, time, length, temperature, volume, count, …',
               existing_comment='Dimension type: mass, time, length, temperature, volume, count, rate, …',
               existing_nullable=False)
    op.drop_column('units_of_measure', 'denominator_uom_id')
    op.drop_column('units_of_measure', 'numerator_uom_id')
    op.alter_column('step_parameters', 'uom',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Unit of measure — FK to units_of_measure.symbol',
               existing_nullable=True)
    op.alter_column('product_definitions', 'uom',
               existing_type=sa.VARCHAR(length=20),
               comment='Unit of measure (EA, KG, L, etc.)',
               existing_comment='Unit of measure — FK to units_of_measure.symbol',
               existing_nullable=False)
    op.drop_index(op.f('ix_plugin_config_id'), table_name='plugin_config')
    op.alter_column('plugin_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag',
               existing_comment='Soft delete flag. False means the entity is logically deleted.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('plugin_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the entity was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plugin_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the entity was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plugin_config', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the entity',
               existing_nullable=False)
    op.alter_column('plugin_config', 'config_overrides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='User-overridden config values (merged over manifest defaults)',
               existing_comment='Additional runtime config overrides (merged over manifest defaults)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('material_definitions', 'uom',
               existing_type=sa.VARCHAR(length=20),
               comment='Default unit of measure (e.g. EA, kg, L)',
               existing_comment='Default unit of measure — FK to units_of_measure.symbol',
               existing_nullable=False)
    op.alter_column('material_definitions', 'material_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Material type: raw, intermediate, finished',
               existing_comment='Material type: raw, intermediate, finished, semi, consumable, packaging, spare',
               existing_nullable=False)
    op.alter_column('data_definitions', 'uom',
               existing_type=sa.VARCHAR(length=20),
               comment='Unit of measure for numeric values (e.g. °C, Nm, mm)',
               existing_comment='Unit of measure — FK to units_of_measure.symbol',
               existing_nullable=True)
    op.alter_column('bom_items', 'uom',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Unit of measure — FK to units_of_measure.symbol',
               existing_nullable=False)
    # ### end Alembic commands ###
