"""add utc timestamp columns

Revision ID: 90a8e6b0846b
Revises: i0j1k2l3m4n5
Create Date: 2026-04-08 08:23:30.969366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90a8e6b0846b'
down_revision: Union[str, None] = 'i0j1k2l3m4n5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('areas', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('bills_of_material', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('bills_of_material', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('bom_items', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('bom_items', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('data_definitions', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('data_definitions', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('data_points', sa.Column('collected_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the data was collected (UTC)'))
    op.add_column('data_points', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('data_points', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('equipment', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('equipment', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('equipment_materials', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('equipment_materials', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('equipment_state_logs', sa.Column('started_at_utc', sa.DateTime(timezone=True), nullable=True, comment='When this state began (UTC)'))
    op.add_column('equipment_state_logs', sa.Column('ended_at_utc', sa.DateTime(timezone=True), nullable=True, comment='When this state ended (UTC)'))
    op.add_column('equipment_state_logs', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('equipment_state_logs', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('equipment_state_models', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('equipment_state_models', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('erp_inbound_orders', sa.Column('next_retry_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Next retry timestamp in UTC (exponential backoff)'))
    op.add_column('erp_inbound_orders', sa.Column('processed_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when successfully processed (UTC)'))
    op.add_column('erp_inbound_orders', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('erp_inbound_orders', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.alter_column('erp_inbound_orders', 'erp_reference',
               existing_type=sa.VARCHAR(length=255),
               comment='ERP-native order identifier (from ProductionOrderDTO)',
               existing_nullable=False)
    op.alter_column('erp_inbound_orders', 'product_code',
               existing_type=sa.VARCHAR(length=100),
               comment='Product code from the ERP order',
               existing_nullable=False)
    op.alter_column('erp_inbound_orders', 'payload',
               existing_type=sa.TEXT(),
               comment='Full ProductionOrderDTO serialized as JSON',
               existing_nullable=False)
    op.alter_column('erp_inbound_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Queue status: pending | processed | failed | retry',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('erp_inbound_orders', 'order_id',
               existing_type=sa.VARCHAR(length=36),
               comment='MES ProductionOrder.id after successful processing',
               existing_nullable=True)
    op.alter_column('erp_inbound_orders', 'wip_ids',
               existing_type=sa.TEXT(),
               comment='JSON list of created Lot/Unit IDs',
               existing_nullable=True)
    op.alter_column('erp_inbound_orders', 'processor_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Name of the OrderProcessor that handled this order',
               existing_nullable=True)
    op.alter_column('erp_inbound_orders', 'attempts',
               existing_type=sa.INTEGER(),
               comment='Number of processing attempts so far',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('erp_inbound_orders', 'max_attempts',
               existing_type=sa.INTEGER(),
               comment='Maximum retry attempts before marking as failed',
               existing_nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('erp_inbound_orders', 'next_retry_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Next retry timestamp (exponential backoff)',
               existing_nullable=True)
    op.alter_column('erp_inbound_orders', 'last_error',
               existing_type=sa.TEXT(),
               comment='Error message from the last failed attempt',
               existing_nullable=True)
    op.alter_column('erp_inbound_orders', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when successfully processed',
               existing_nullable=True)
    op.alter_column('erp_inbound_orders', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the entity',
               existing_nullable=False)
    op.alter_column('erp_inbound_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the entity was created',
               existing_nullable=False)
    op.alter_column('erp_inbound_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the entity was last updated',
               existing_nullable=False)
    op.alter_column('erp_inbound_orders', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag. False means the entity is logically deleted.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_erp_inbound_orders_id'), 'erp_inbound_orders', ['id'], unique=False)
    op.add_column('erp_outbound_queue', sa.Column('next_retry_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Next retry timestamp in UTC (exponential backoff)'))
    op.add_column('erp_outbound_queue', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('erp_outbound_queue', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('idp_group_mappings', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('idp_group_mappings', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('lot_history', sa.Column('entered_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the lot entered this step (UTC)'))
    op.add_column('lot_history', sa.Column('exited_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the lot left this step (UTC)'))
    op.add_column('lot_history', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('lot_history', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('lots', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('lots', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('material_consumptions', sa.Column('consumed_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when consumption was recorded (UTC)'))
    op.add_column('material_consumptions', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('material_consumptions', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('material_definitions', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('material_definitions', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('material_lots', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('material_lots', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('non_conformances', sa.Column('resolved_at_utc', sa.DateTime(timezone=True), nullable=True))
    op.add_column('non_conformances', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('non_conformances', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('permissions', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('permissions', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('plugin_config', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('plugin_config', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('process_routes', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('process_routes', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.alter_column('process_routes', 'product_id',
               existing_type=sa.UUID(),
               comment='Legacy 1:1 product FK. Nullable — use route_product_assignments for many:many.',
               existing_nullable=True)
    op.add_column('product_definitions', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('product_definitions', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('production_counters', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('production_counters', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('production_lines', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('production_lines', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('production_orders', sa.Column('planned_start_utc', sa.DateTime(timezone=True), nullable=True))
    op.add_column('production_orders', sa.Column('planned_end_utc', sa.DateTime(timezone=True), nullable=True))
    op.add_column('production_orders', sa.Column('actual_start_utc', sa.DateTime(timezone=True), nullable=True))
    op.add_column('production_orders', sa.Column('actual_end_utc', sa.DateTime(timezone=True), nullable=True))
    op.add_column('production_orders', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('production_orders', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('quality_tests', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('quality_tests', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('reasons', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('reasons', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('roles', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('roles', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('route_material_assignments', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('route_material_assignments', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.alter_column('route_material_assignments', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the entity',
               existing_nullable=False)
    op.alter_column('route_material_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the entity was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('route_material_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the entity was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('route_material_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag. False means the entity is logically deleted.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('uq_route_material'), 'route_material_assignments', type_='unique')
    op.create_index(op.f('ix_route_material_assignments_id'), 'route_material_assignments', ['id'], unique=False)
    op.add_column('route_product_assignments', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('route_product_assignments', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.alter_column('route_product_assignments', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the entity',
               existing_nullable=False)
    op.alter_column('route_product_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the entity was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('route_product_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the entity was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('route_product_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag. False means the entity is logically deleted.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('uq_route_product'), 'route_product_assignments', type_='unique')
    op.create_index(op.f('ix_route_product_assignments_id'), 'route_product_assignments', ['id'], unique=False)
    op.add_column('route_steps', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('route_steps', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('sites', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('sites', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('step_parameters', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('step_parameters', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('step_transitions', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('step_transitions', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('test_results', sa.Column('tested_at_utc', sa.DateTime(timezone=True), nullable=True, comment='When the test was performed (UTC)'))
    op.add_column('test_results', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('test_results', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('unit_history', sa.Column('entered_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the unit entered this step (UTC)'))
    op.add_column('unit_history', sa.Column('exited_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the unit left this step (UTC)'))
    op.add_column('unit_history', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('unit_history', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('units', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('units', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('units_of_measure', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('units_of_measure', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('user_roles', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('user_roles', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('users', sa.Column('last_login_utc', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('users', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.add_column('work_cells', sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('work_cells', sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))

    # ── Populate _utc columns from existing (already UTC) timestamps ──
    # All tables inherit created_at / updated_at from BaseModel
    all_tables = [
        'areas', 'bills_of_material', 'bom_items', 'data_definitions',
        'data_points', 'equipment', 'equipment_materials',
        'equipment_state_logs', 'equipment_state_models',
        'erp_inbound_orders', 'erp_outbound_queue', 'idp_group_mappings',
        'lot_history', 'lots', 'material_consumptions',
        'material_definitions', 'material_lots', 'non_conformances',
        'permissions', 'plugin_config', 'process_routes',
        'product_definitions', 'production_counters', 'production_lines',
        'production_orders', 'quality_tests', 'reasons', 'roles',
        'route_material_assignments', 'route_product_assignments',
        'route_steps', 'sites', 'step_parameters', 'step_transitions',
        'test_results', 'unit_history', 'units', 'units_of_measure',
        'user_roles', 'users', 'work_cells',
    ]
    for tbl in all_tables:
        op.execute(
            f"UPDATE {tbl} SET created_at_utc = created_at, updated_at_utc = updated_at"
        )

    # Model-specific timestamp columns
    op.execute("UPDATE production_orders SET planned_start_utc = planned_start, planned_end_utc = planned_end, actual_start_utc = actual_start, actual_end_utc = actual_end")
    op.execute("UPDATE unit_history SET entered_at_utc = entered_at, exited_at_utc = exited_at")
    op.execute("UPDATE lot_history SET entered_at_utc = entered_at, exited_at_utc = exited_at")
    op.execute("UPDATE data_points SET collected_at_utc = collected_at")
    op.execute("UPDATE test_results SET tested_at_utc = tested_at")
    op.execute("UPDATE non_conformances SET resolved_at_utc = resolved_at")
    op.execute("UPDATE equipment_state_logs SET started_at_utc = started_at, ended_at_utc = ended_at")
    op.execute("UPDATE erp_outbound_queue SET next_retry_at_utc = next_retry_at")
    op.execute("UPDATE erp_inbound_orders SET next_retry_at_utc = next_retry_at, processed_at_utc = processed_at")
    op.execute("UPDATE material_consumptions SET consumed_at_utc = consumed_at")
    op.execute("UPDATE users SET last_login_utc = last_login")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_cells', 'updated_at_utc')
    op.drop_column('work_cells', 'created_at_utc')
    op.drop_column('users', 'updated_at_utc')
    op.drop_column('users', 'created_at_utc')
    op.drop_column('users', 'last_login_utc')
    op.drop_column('user_roles', 'updated_at_utc')
    op.drop_column('user_roles', 'created_at_utc')
    op.drop_column('units_of_measure', 'updated_at_utc')
    op.drop_column('units_of_measure', 'created_at_utc')
    op.drop_column('units', 'updated_at_utc')
    op.drop_column('units', 'created_at_utc')
    op.drop_column('unit_history', 'updated_at_utc')
    op.drop_column('unit_history', 'created_at_utc')
    op.drop_column('unit_history', 'exited_at_utc')
    op.drop_column('unit_history', 'entered_at_utc')
    op.drop_column('test_results', 'updated_at_utc')
    op.drop_column('test_results', 'created_at_utc')
    op.drop_column('test_results', 'tested_at_utc')
    op.drop_column('step_transitions', 'updated_at_utc')
    op.drop_column('step_transitions', 'created_at_utc')
    op.drop_column('step_parameters', 'updated_at_utc')
    op.drop_column('step_parameters', 'created_at_utc')
    op.drop_column('sites', 'updated_at_utc')
    op.drop_column('sites', 'created_at_utc')
    op.drop_column('route_steps', 'updated_at_utc')
    op.drop_column('route_steps', 'created_at_utc')
    op.drop_index(op.f('ix_route_product_assignments_id'), table_name='route_product_assignments')
    op.create_unique_constraint(op.f('uq_route_product'), 'route_product_assignments', ['route_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('route_product_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag. False means the entity is logically deleted.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('route_product_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the entity was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('route_product_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the entity was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('route_product_assignments', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the entity',
               existing_nullable=False)
    op.drop_column('route_product_assignments', 'updated_at_utc')
    op.drop_column('route_product_assignments', 'created_at_utc')
    op.drop_index(op.f('ix_route_material_assignments_id'), table_name='route_material_assignments')
    op.create_unique_constraint(op.f('uq_route_material'), 'route_material_assignments', ['route_id', 'material_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('route_material_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag. False means the entity is logically deleted.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('route_material_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the entity was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('route_material_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the entity was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('route_material_assignments', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the entity',
               existing_nullable=False)
    op.drop_column('route_material_assignments', 'updated_at_utc')
    op.drop_column('route_material_assignments', 'created_at_utc')
    op.drop_column('roles', 'updated_at_utc')
    op.drop_column('roles', 'created_at_utc')
    op.drop_column('reasons', 'updated_at_utc')
    op.drop_column('reasons', 'created_at_utc')
    op.drop_column('quality_tests', 'updated_at_utc')
    op.drop_column('quality_tests', 'created_at_utc')
    op.drop_column('production_orders', 'updated_at_utc')
    op.drop_column('production_orders', 'created_at_utc')
    op.drop_column('production_orders', 'actual_end_utc')
    op.drop_column('production_orders', 'actual_start_utc')
    op.drop_column('production_orders', 'planned_end_utc')
    op.drop_column('production_orders', 'planned_start_utc')
    op.drop_column('production_lines', 'updated_at_utc')
    op.drop_column('production_lines', 'created_at_utc')
    op.drop_column('production_counters', 'updated_at_utc')
    op.drop_column('production_counters', 'created_at_utc')
    op.drop_column('product_definitions', 'updated_at_utc')
    op.drop_column('product_definitions', 'created_at_utc')
    op.alter_column('process_routes', 'product_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Legacy 1:1 product FK. Nullable — use route_product_assignments for many:many.',
               existing_nullable=True)
    op.drop_column('process_routes', 'updated_at_utc')
    op.drop_column('process_routes', 'created_at_utc')
    op.drop_column('plugin_config', 'updated_at_utc')
    op.drop_column('plugin_config', 'created_at_utc')
    op.drop_column('permissions', 'updated_at_utc')
    op.drop_column('permissions', 'created_at_utc')
    op.drop_column('non_conformances', 'updated_at_utc')
    op.drop_column('non_conformances', 'created_at_utc')
    op.drop_column('non_conformances', 'resolved_at_utc')
    op.drop_column('material_lots', 'updated_at_utc')
    op.drop_column('material_lots', 'created_at_utc')
    op.drop_column('material_definitions', 'updated_at_utc')
    op.drop_column('material_definitions', 'created_at_utc')
    op.drop_column('material_consumptions', 'updated_at_utc')
    op.drop_column('material_consumptions', 'created_at_utc')
    op.drop_column('material_consumptions', 'consumed_at_utc')
    op.drop_column('lots', 'updated_at_utc')
    op.drop_column('lots', 'created_at_utc')
    op.drop_column('lot_history', 'updated_at_utc')
    op.drop_column('lot_history', 'created_at_utc')
    op.drop_column('lot_history', 'exited_at_utc')
    op.drop_column('lot_history', 'entered_at_utc')
    op.drop_column('idp_group_mappings', 'updated_at_utc')
    op.drop_column('idp_group_mappings', 'created_at_utc')
    op.drop_column('erp_outbound_queue', 'updated_at_utc')
    op.drop_column('erp_outbound_queue', 'created_at_utc')
    op.drop_column('erp_outbound_queue', 'next_retry_at_utc')
    op.drop_index(op.f('ix_erp_inbound_orders_id'), table_name='erp_inbound_orders')
    op.alter_column('erp_inbound_orders', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag. False means the entity is logically deleted.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('erp_inbound_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the entity was last updated',
               existing_nullable=False)
    op.alter_column('erp_inbound_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the entity was created',
               existing_nullable=False)
    op.alter_column('erp_inbound_orders', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the entity',
               existing_nullable=False)
    op.alter_column('erp_inbound_orders', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when successfully processed',
               existing_nullable=True)
    op.alter_column('erp_inbound_orders', 'last_error',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error message from the last failed attempt',
               existing_nullable=True)
    op.alter_column('erp_inbound_orders', 'next_retry_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Next retry timestamp (exponential backoff)',
               existing_nullable=True)
    op.alter_column('erp_inbound_orders', 'max_attempts',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Maximum retry attempts before marking as failed',
               existing_nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('erp_inbound_orders', 'attempts',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of processing attempts so far',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('erp_inbound_orders', 'processor_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Name of the OrderProcessor that handled this order',
               existing_nullable=True)
    op.alter_column('erp_inbound_orders', 'wip_ids',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON list of created Lot/Unit IDs',
               existing_nullable=True)
    op.alter_column('erp_inbound_orders', 'order_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='MES ProductionOrder.id after successful processing',
               existing_nullable=True)
    op.alter_column('erp_inbound_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Queue status: pending | processed | failed | retry',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('erp_inbound_orders', 'payload',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Full ProductionOrderDTO serialized as JSON',
               existing_nullable=False)
    op.alter_column('erp_inbound_orders', 'product_code',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Product code from the ERP order',
               existing_nullable=False)
    op.alter_column('erp_inbound_orders', 'erp_reference',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='ERP-native order identifier (from ProductionOrderDTO)',
               existing_nullable=False)
    op.drop_column('erp_inbound_orders', 'updated_at_utc')
    op.drop_column('erp_inbound_orders', 'created_at_utc')
    op.drop_column('erp_inbound_orders', 'processed_at_utc')
    op.drop_column('erp_inbound_orders', 'next_retry_at_utc')
    op.drop_column('equipment_state_models', 'updated_at_utc')
    op.drop_column('equipment_state_models', 'created_at_utc')
    op.drop_column('equipment_state_logs', 'updated_at_utc')
    op.drop_column('equipment_state_logs', 'created_at_utc')
    op.drop_column('equipment_state_logs', 'ended_at_utc')
    op.drop_column('equipment_state_logs', 'started_at_utc')
    op.drop_column('equipment_materials', 'updated_at_utc')
    op.drop_column('equipment_materials', 'created_at_utc')
    op.drop_column('equipment', 'updated_at_utc')
    op.drop_column('equipment', 'created_at_utc')
    op.drop_column('data_points', 'updated_at_utc')
    op.drop_column('data_points', 'created_at_utc')
    op.drop_column('data_points', 'collected_at_utc')
    op.drop_column('data_definitions', 'updated_at_utc')
    op.drop_column('data_definitions', 'created_at_utc')
    op.drop_column('bom_items', 'updated_at_utc')
    op.drop_column('bom_items', 'created_at_utc')
    op.drop_column('bills_of_material', 'updated_at_utc')
    op.drop_column('bills_of_material', 'created_at_utc')
    op.drop_column('areas', 'updated_at_utc')
    op.drop_column('areas', 'created_at_utc')
    # ### end Alembic commands ###
