"""initial schema layers 0-4

Revision ID: 4c0016b2fcbc
Revises: 
Create Date: 2026-02-27 17:44:38.046038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0016b2fcbc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_definitions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique material code (SKU / part number)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('material_type', sa.String(length=20), nullable=False, comment='Material type: raw, intermediate, finished'),
    sa.Column('uom', sa.String(length=20), nullable=False, comment='Default unit of measure (e.g. EA, kg, L)'),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True, comment='Shelf life in days from receipt. Null means no expiry.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_definitions_code'), 'material_definitions', ['code'], unique=True)
    op.create_index(op.f('ix_material_definitions_id'), 'material_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_material_definitions_name'), 'material_definitions', ['name'], unique=False)
    op.create_table('product_definitions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False, comment='Product version — allows multiple revisions of a product code'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=False, comment='Unit of measure (EA, KG, L, etc.)'),
    sa.Column('product_type', sa.String(length=20), nullable=False, comment="Product type: 'discrete' or 'process'"),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_definitions_code'), 'product_definitions', ['code'], unique=False)
    op.create_index(op.f('ix_product_definitions_id'), 'product_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_product_definitions_name'), 'product_definitions', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='True for built-in roles that cannot be deleted'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('sites',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment="IANA timezone identifier (e.g. 'America/Chicago')"),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_code'), 'sites', ['code'], unique=True)
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=False)
    op.create_table('units_of_measure',
    sa.Column('symbol', sa.String(length=20), nullable=False, comment="Short symbol, e.g. 'kg', 'lb', 'case'"),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Human-friendly name, e.g. 'kilogram'"),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional longer description'),
    sa.Column('uom_type', sa.String(length=50), nullable=False, comment='Dimension type: mass, time, length, temperature, volume, count, …'),
    sa.Column('multiplier', sa.Float(), nullable=False, comment="Multiplier relative to the type's base unit"),
    sa.Column('offset', sa.Float(), nullable=False, comment='Offset for affine conversions (used by temperature)'),
    sa.Column('is_builtin', sa.Boolean(), nullable=False, comment='True for seed/out-of-the-box units — prevents deletion'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_of_measure_id'), 'units_of_measure', ['id'], unique=False)
    op.create_index(op.f('ix_units_of_measure_symbol'), 'units_of_measure', ['symbol'], unique=True)
    op.create_index(op.f('ix_units_of_measure_uom_type'), 'units_of_measure', ['uom_type'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('idp_subject', sa.String(length=255), nullable=True, comment="OIDC 'sub' claim — unique user ID at the IdP"),
    sa.Column('idp_issuer', sa.String(length=512), nullable=True, comment="OIDC 'iss' claim — identifies which IdP issued the token"),
    sa.Column('hashed_password', sa.Text(), nullable=True, comment='bcrypt hash; only populated when auth_mode=local'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_idp_subject'), 'users', ['idp_subject'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('areas',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_code'), 'areas', ['code'], unique=True)
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_index(op.f('ix_areas_name'), 'areas', ['name'], unique=False)
    op.create_index(op.f('ix_areas_site_id'), 'areas', ['site_id'], unique=False)
    op.create_table('bills_of_material',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False, comment='BOM version — allows multiple BOM revisions per product'),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['product_id'], ['product_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_of_material_id'), 'bills_of_material', ['id'], unique=False)
    op.create_index(op.f('ix_bills_of_material_product_id'), 'bills_of_material', ['product_id'], unique=False)
    op.create_table('idp_group_mappings',
    sa.Column('idp_group', sa.String(length=255), nullable=False, comment="Group name as it appears in the IdP 'groups' claim"),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idp_group_mappings_id'), 'idp_group_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_idp_group_mappings_idp_group'), 'idp_group_mappings', ['idp_group'], unique=False)
    op.create_index(op.f('ix_idp_group_mappings_role_id'), 'idp_group_mappings', ['role_id'], unique=False)
    op.create_table('material_lots',
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('lot_number', sa.String(length=200), nullable=False, comment='Unique lot identifier (supplier lot number or internal batch ID)'),
    sa.Column('quantity_on_hand', sa.Float(), nullable=False, comment='Current quantity available'),
    sa.Column('quantity_reserved', sa.Float(), nullable=False, comment='Quantity reserved for specific orders but not yet consumed'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Lot status: available, reserved, consumed, expired'),
    sa.Column('received_date', sa.Date(), nullable=True, comment='Date the lot was received into inventory'),
    sa.Column('expiry_date', sa.Date(), nullable=True, comment='Expiry date (auto-calculated from shelf_life_days if set)'),
    sa.Column('supplier', sa.String(length=255), nullable=True, comment='Supplier name or identifier'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['material_id'], ['material_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_lots_id'), 'material_lots', ['id'], unique=False)
    op.create_index(op.f('ix_material_lots_lot_number'), 'material_lots', ['lot_number'], unique=True)
    op.create_index(op.f('ix_material_lots_material_id'), 'material_lots', ['material_id'], unique=False)
    op.create_table('permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=255), nullable=False, comment="Dot-notation permission string (e.g. 'wip.unit.move', 'quality.*')"),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_permission'), 'permissions', ['permission'], unique=False)
    op.create_index(op.f('ix_permissions_role_id'), 'permissions', ['role_id'], unique=False)
    op.create_table('process_routes',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Only one route per product should be marked as default'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['product_id'], ['product_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_routes_id'), 'process_routes', ['id'], unique=False)
    op.create_index(op.f('ix_process_routes_name'), 'process_routes', ['name'], unique=False)
    op.create_index(op.f('ix_process_routes_product_id'), 'process_routes', ['product_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('bom_items',
    sa.Column('bom_id', sa.UUID(), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False, comment='Material code reference. Will become FK to material_definitions when MAT-MGMT is implemented.'),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, comment='Sort order within the BOM'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['bom_id'], ['bills_of_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_items_bom_id'), 'bom_items', ['bom_id'], unique=False)
    op.create_index(op.f('ix_bom_items_id'), 'bom_items', ['id'], unique=False)
    op.create_table('production_lines',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_lines_area_id'), 'production_lines', ['area_id'], unique=False)
    op.create_index(op.f('ix_production_lines_code'), 'production_lines', ['code'], unique=True)
    op.create_index(op.f('ix_production_lines_id'), 'production_lines', ['id'], unique=False)
    op.create_index(op.f('ix_production_lines_name'), 'production_lines', ['name'], unique=False)
    op.create_table('production_orders',
    sa.Column('order_number', sa.String(length=100), nullable=False, comment='Business-visible order number (may come from ERP)'),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=True, comment="Assigned process route; null means use product's default route"),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False, comment='Total quantity to produce'),
    sa.Column('quantity_completed', sa.Integer(), nullable=False, comment='Quantity successfully completed'),
    sa.Column('quantity_scrapped', sa.Integer(), nullable=False, comment='Quantity scrapped during production'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Order status: created, released, in_progress, completed, closed'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Priority (higher = more urgent). 0 = normal.'),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erp_reference', sa.String(length=255), nullable=True, comment='External reference from ERP system'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['product_id'], ['product_definitions.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['process_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_id'), 'production_orders', ['id'], unique=False)
    op.create_index(op.f('ix_production_orders_order_number'), 'production_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_production_orders_product_id'), 'production_orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_production_orders_route_id'), 'production_orders', ['route_id'], unique=False)
    op.create_table('work_cells',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('wc_type', sa.String(length=20), nullable=False, comment="Work cell type: 'manual' or 'automated'"),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_cells_code'), 'work_cells', ['code'], unique=True)
    op.create_index(op.f('ix_work_cells_id'), 'work_cells', ['id'], unique=False)
    op.create_index(op.f('ix_work_cells_line_id'), 'work_cells', ['line_id'], unique=False)
    op.create_index(op.f('ix_work_cells_name'), 'work_cells', ['name'], unique=False)
    op.create_table('equipment',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_cell_id', sa.UUID(), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=True, comment='Free-form equipment type classification'),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Operational status: 'up', 'down', 'idle'"),
    sa.Column('capabilities', sa.JSON(), nullable=True, comment='Freeform JSON describing equipment capabilities for dispatch matching'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['work_cell_id'], ['work_cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_code'), 'equipment', ['code'], unique=True)
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=False)
    op.create_index(op.f('ix_equipment_work_cell_id'), 'equipment', ['work_cell_id'], unique=False)
    op.create_table('route_steps',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='Step sequence number (10, 20, 30 convention for easy insertion)'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('step_type', sa.String(length=20), nullable=False, comment="Step type: 'production', 'inspection', or 'rework'"),
    sa.Column('work_cell_id', sa.UUID(), nullable=True, comment='Work cell where this step is performed (nullable for unassigned steps)'),
    sa.Column('expected_cycle_time_sec', sa.Float(), nullable=True, comment='Expected cycle time in seconds for performance analysis'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['route_id'], ['process_routes.id'], ),
    sa.ForeignKeyConstraint(['work_cell_id'], ['work_cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_steps_id'), 'route_steps', ['id'], unique=False)
    op.create_index(op.f('ix_route_steps_route_id'), 'route_steps', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_steps_work_cell_id'), 'route_steps', ['work_cell_id'], unique=False)
    op.create_table('data_definitions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique definition code (e.g. TEMP-OVEN-1, TORQUE-BOLT-A)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=False, comment='Expected data type: numeric, string, boolean, enum'),
    sa.Column('uom', sa.String(length=20), nullable=True, comment='Unit of measure for numeric values (e.g. °C, Nm, mm)'),
    sa.Column('step_id', sa.UUID(), nullable=True, comment='Route step where this data is collected (null = any step)'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='Data source: manual, equipment, sensor'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='If true, this data point must be collected before step completion'),
    sa.Column('enum_values', sa.Text(), nullable=True, comment="Comma-separated allowed values when data_type='enum'"),
    sa.Column('lower_limit', sa.Float(), nullable=True, comment='Lower acceptable limit for numeric values'),
    sa.Column('upper_limit', sa.Float(), nullable=True, comment='Upper acceptable limit for numeric values'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['step_id'], ['route_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_definitions_code'), 'data_definitions', ['code'], unique=True)
    op.create_index(op.f('ix_data_definitions_id'), 'data_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_data_definitions_name'), 'data_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_data_definitions_step_id'), 'data_definitions', ['step_id'], unique=False)
    op.create_table('equipment_state_logs',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('state_model', sa.String(length=50), nullable=False, comment="State model plugin ID (e.g. 'packml', 'semi_e10', 'oee_tpm')"),
    sa.Column('state', sa.String(length=50), nullable=False, comment="Plugin-specific state name (e.g. 'Execute', 'Idle')"),
    sa.Column('sub_state', sa.String(length=50), nullable=True, comment='Optional sub-state within the state'),
    sa.Column('dispatch_category', sa.String(length=30), nullable=False, comment='Canonical dispatch category: available, busy, unavailable_planned, unavailable_unplanned'),
    sa.Column('oee_bucket', sa.String(length=30), nullable=False, comment='OEE bucket: uptime_value_add, uptime_non_value, downtime_planned, downtime_unplanned, excluded'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='When this state began'),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True, comment='When this state ended (null = current state)'),
    sa.Column('reason_code', sa.String(length=50), nullable=True, comment='Optional reason code for the state change'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_state_logs_equipment_id'), 'equipment_state_logs', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_equipment_state_logs_id'), 'equipment_state_logs', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_state_logs_started_at'), 'equipment_state_logs', ['started_at'], unique=False)
    op.create_table('lots',
    sa.Column('lot_number', sa.String(length=200), nullable=False, comment='Unique lot identifier'),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Total quantity in this lot'),
    sa.Column('current_step_id', sa.UUID(), nullable=True),
    sa.Column('current_equipment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Lot status: queued, in_process, completed, scrapped, on_hold'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['current_equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['current_step_id'], ['route_steps.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lots_current_equipment_id'), 'lots', ['current_equipment_id'], unique=False)
    op.create_index(op.f('ix_lots_current_step_id'), 'lots', ['current_step_id'], unique=False)
    op.create_index(op.f('ix_lots_id'), 'lots', ['id'], unique=False)
    op.create_index(op.f('ix_lots_lot_number'), 'lots', ['lot_number'], unique=True)
    op.create_index(op.f('ix_lots_order_id'), 'lots', ['order_id'], unique=False)
    op.create_index(op.f('ix_lots_product_id'), 'lots', ['product_id'], unique=False)
    op.create_table('production_counters',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('shift_date', sa.Date(), nullable=False, comment='The calendar date of the shift'),
    sa.Column('good_count', sa.Integer(), nullable=False),
    sa.Column('reject_count', sa.Integer(), nullable=False),
    sa.Column('rework_count', sa.Integer(), nullable=False),
    sa.Column('ideal_cycle_time_sec', sa.Float(), nullable=True, comment='Ideal cycle time in seconds for this product/equipment combo'),
    sa.Column('actual_run_time_sec', sa.Float(), nullable=True, comment='Actual productive run time in seconds for the shift'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_counters_equipment_id'), 'production_counters', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_production_counters_id'), 'production_counters', ['id'], unique=False)
    op.create_index(op.f('ix_production_counters_order_id'), 'production_counters', ['order_id'], unique=False)
    op.create_index(op.f('ix_production_counters_shift_date'), 'production_counters', ['shift_date'], unique=False)
    op.create_table('quality_tests',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique test code'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('test_type', sa.String(length=20), nullable=False, comment='Test type: inline, offline, destructive'),
    sa.Column('step_id', sa.UUID(), nullable=True, comment='Optional route step where this test is performed'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='JSON describing test parameters, criteria, and tolerances'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['step_id'], ['route_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_tests_code'), 'quality_tests', ['code'], unique=True)
    op.create_index(op.f('ix_quality_tests_id'), 'quality_tests', ['id'], unique=False)
    op.create_index(op.f('ix_quality_tests_name'), 'quality_tests', ['name'], unique=False)
    op.create_index(op.f('ix_quality_tests_step_id'), 'quality_tests', ['step_id'], unique=False)
    op.create_table('step_parameters',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False, comment="Data type: 'numeric', 'string', 'boolean', 'enum'"),
    sa.Column('uom', sa.String(length=20), nullable=True),
    sa.Column('target_value', sa.String(length=255), nullable=True, comment='Target/nominal value as string (parsed based on data_type)'),
    sa.Column('lower_limit', sa.String(length=255), nullable=True, comment='Lower control/spec limit'),
    sa.Column('upper_limit', sa.String(length=255), nullable=True, comment='Upper control/spec limit'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='Whether data collection for this parameter is mandatory'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['step_id'], ['route_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_parameters_id'), 'step_parameters', ['id'], unique=False)
    op.create_index(op.f('ix_step_parameters_step_id'), 'step_parameters', ['step_id'], unique=False)
    op.create_table('units',
    sa.Column('serial_number', sa.String(length=200), nullable=False, comment='Unique serial number for the unit'),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('current_step_id', sa.UUID(), nullable=True, comment='The route step where the unit currently sits (null if completed or not started)'),
    sa.Column('current_equipment_id', sa.UUID(), nullable=True, comment='Equipment currently processing the unit (null if queued/completed)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Unit status: queued, in_process, completed, scrapped, on_hold'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['current_equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['current_step_id'], ['route_steps.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_current_equipment_id'), 'units', ['current_equipment_id'], unique=False)
    op.create_index(op.f('ix_units_current_step_id'), 'units', ['current_step_id'], unique=False)
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_index(op.f('ix_units_order_id'), 'units', ['order_id'], unique=False)
    op.create_index(op.f('ix_units_product_id'), 'units', ['product_id'], unique=False)
    op.create_index(op.f('ix_units_serial_number'), 'units', ['serial_number'], unique=True)
    op.create_table('data_points',
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True, comment='WIP unit this data was collected for (null if lot-based)'),
    sa.Column('lot_id', sa.UUID(), nullable=True, comment='WIP lot this data was collected for (null if unit-based)'),
    sa.Column('value_numeric', sa.Float(), nullable=True, comment="Collected value when data_type='numeric'"),
    sa.Column('value_string', sa.Text(), nullable=True, comment="Collected value when data_type='string' or 'enum'"),
    sa.Column('value_boolean', sa.Boolean(), nullable=True, comment="Collected value when data_type='boolean'"),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the data was collected'),
    sa.Column('source_equipment_id', sa.UUID(), nullable=True, comment='Equipment that produced this data (null if manual entry)'),
    sa.Column('operator_id', sa.UUID(), nullable=True, comment='Operator who entered/confirmed this data'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['definition_id'], ['data_definitions.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_points_definition_id'), 'data_points', ['definition_id'], unique=False)
    op.create_index(op.f('ix_data_points_id'), 'data_points', ['id'], unique=False)
    op.create_index(op.f('ix_data_points_lot_id'), 'data_points', ['lot_id'], unique=False)
    op.create_index(op.f('ix_data_points_operator_id'), 'data_points', ['operator_id'], unique=False)
    op.create_index(op.f('ix_data_points_source_equipment_id'), 'data_points', ['source_equipment_id'], unique=False)
    op.create_index(op.f('ix_data_points_unit_id'), 'data_points', ['unit_id'], unique=False)
    op.create_table('lot_history',
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity_in', sa.Integer(), nullable=False, comment='Quantity entering this step'),
    sa.Column('quantity_out', sa.Integer(), nullable=False, comment='Quantity completing this step successfully'),
    sa.Column('quantity_scrapped', sa.Integer(), nullable=False, comment='Quantity scrapped at this step'),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['route_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_history_equipment_id'), 'lot_history', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_lot_history_id'), 'lot_history', ['id'], unique=False)
    op.create_index(op.f('ix_lot_history_lot_id'), 'lot_history', ['lot_id'], unique=False)
    op.create_index(op.f('ix_lot_history_step_id'), 'lot_history', ['step_id'], unique=False)
    op.create_table('material_consumptions',
    sa.Column('material_lot_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True, comment='WIP unit that consumed this material (null if lot-based)'),
    sa.Column('lot_id', sa.UUID(), nullable=True, comment='WIP lot that consumed this material (null if unit-based)'),
    sa.Column('step_id', sa.UUID(), nullable=True, comment='Route step at which consumption occurred'),
    sa.Column('quantity_consumed', sa.Float(), nullable=False, comment='Quantity of material consumed'),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when consumption was recorded'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['material_lot_id'], ['material_lots.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['route_steps.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_consumptions_id'), 'material_consumptions', ['id'], unique=False)
    op.create_index(op.f('ix_material_consumptions_lot_id'), 'material_consumptions', ['lot_id'], unique=False)
    op.create_index(op.f('ix_material_consumptions_material_lot_id'), 'material_consumptions', ['material_lot_id'], unique=False)
    op.create_index(op.f('ix_material_consumptions_step_id'), 'material_consumptions', ['step_id'], unique=False)
    op.create_index(op.f('ix_material_consumptions_unit_id'), 'material_consumptions', ['unit_id'], unique=False)
    op.create_table('non_conformances',
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True, comment='Route step where the non-conformance was detected'),
    sa.Column('nc_type', sa.String(length=20), nullable=False, comment='Non-conformance type: defect, out_of_spec, other'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed description of the non-conformance'),
    sa.Column('disposition', sa.String(length=20), nullable=True, comment='Disposition: rework, scrap, use_as_is, return (null until resolved)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Workflow status: open, investigating, resolved, closed'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['route_steps.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_non_conformances_id'), 'non_conformances', ['id'], unique=False)
    op.create_index(op.f('ix_non_conformances_lot_id'), 'non_conformances', ['lot_id'], unique=False)
    op.create_index(op.f('ix_non_conformances_step_id'), 'non_conformances', ['step_id'], unique=False)
    op.create_index(op.f('ix_non_conformances_unit_id'), 'non_conformances', ['unit_id'], unique=False)
    op.create_table('test_results',
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True, comment='Unit tested (null if lot-level test)'),
    sa.Column('lot_id', sa.UUID(), nullable=True, comment='Lot tested (null if unit-level test)'),
    sa.Column('result', sa.String(length=10), nullable=False, comment='Test result: pass, fail'),
    sa.Column('measured_values', sa.JSON(), nullable=True, comment='JSON of measured values (e.g. {"dimension_a": 10.5})'),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('equipment_id', sa.UUID(), nullable=True, comment='Test equipment used'),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=False, comment='When the test was performed'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['quality_tests.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_equipment_id'), 'test_results', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.create_index(op.f('ix_test_results_lot_id'), 'test_results', ['lot_id'], unique=False)
    op.create_index(op.f('ix_test_results_operator_id'), 'test_results', ['operator_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_id'), 'test_results', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_results_unit_id'), 'test_results', ['unit_id'], unique=False)
    op.create_table('unit_history',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the unit entered this step'),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the unit left this step (null if still in-process)'),
    sa.Column('result', sa.String(length=20), nullable=True, comment='Step result: pass, fail, rework (null if still in-process)'),
    sa.Column('operator_id', sa.UUID(), nullable=True, comment='User ID of the operator (from AUTH module)'),
    sa.Column('data_snapshot', sa.JSON(), nullable=True, comment='Freeform JSON snapshot of data collected at this step'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['route_steps.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_history_equipment_id'), 'unit_history', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_unit_history_id'), 'unit_history', ['id'], unique=False)
    op.create_index(op.f('ix_unit_history_step_id'), 'unit_history', ['step_id'], unique=False)
    op.create_index(op.f('ix_unit_history_unit_id'), 'unit_history', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_history_unit_id'), table_name='unit_history')
    op.drop_index(op.f('ix_unit_history_step_id'), table_name='unit_history')
    op.drop_index(op.f('ix_unit_history_id'), table_name='unit_history')
    op.drop_index(op.f('ix_unit_history_equipment_id'), table_name='unit_history')
    op.drop_table('unit_history')
    op.drop_index(op.f('ix_test_results_unit_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_test_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_operator_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_lot_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_equipment_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_non_conformances_unit_id'), table_name='non_conformances')
    op.drop_index(op.f('ix_non_conformances_step_id'), table_name='non_conformances')
    op.drop_index(op.f('ix_non_conformances_lot_id'), table_name='non_conformances')
    op.drop_index(op.f('ix_non_conformances_id'), table_name='non_conformances')
    op.drop_table('non_conformances')
    op.drop_index(op.f('ix_material_consumptions_unit_id'), table_name='material_consumptions')
    op.drop_index(op.f('ix_material_consumptions_step_id'), table_name='material_consumptions')
    op.drop_index(op.f('ix_material_consumptions_material_lot_id'), table_name='material_consumptions')
    op.drop_index(op.f('ix_material_consumptions_lot_id'), table_name='material_consumptions')
    op.drop_index(op.f('ix_material_consumptions_id'), table_name='material_consumptions')
    op.drop_table('material_consumptions')
    op.drop_index(op.f('ix_lot_history_step_id'), table_name='lot_history')
    op.drop_index(op.f('ix_lot_history_lot_id'), table_name='lot_history')
    op.drop_index(op.f('ix_lot_history_id'), table_name='lot_history')
    op.drop_index(op.f('ix_lot_history_equipment_id'), table_name='lot_history')
    op.drop_table('lot_history')
    op.drop_index(op.f('ix_data_points_unit_id'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_source_equipment_id'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_operator_id'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_lot_id'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_id'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_definition_id'), table_name='data_points')
    op.drop_table('data_points')
    op.drop_index(op.f('ix_units_serial_number'), table_name='units')
    op.drop_index(op.f('ix_units_product_id'), table_name='units')
    op.drop_index(op.f('ix_units_order_id'), table_name='units')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_index(op.f('ix_units_current_step_id'), table_name='units')
    op.drop_index(op.f('ix_units_current_equipment_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_step_parameters_step_id'), table_name='step_parameters')
    op.drop_index(op.f('ix_step_parameters_id'), table_name='step_parameters')
    op.drop_table('step_parameters')
    op.drop_index(op.f('ix_quality_tests_step_id'), table_name='quality_tests')
    op.drop_index(op.f('ix_quality_tests_name'), table_name='quality_tests')
    op.drop_index(op.f('ix_quality_tests_id'), table_name='quality_tests')
    op.drop_index(op.f('ix_quality_tests_code'), table_name='quality_tests')
    op.drop_table('quality_tests')
    op.drop_index(op.f('ix_production_counters_shift_date'), table_name='production_counters')
    op.drop_index(op.f('ix_production_counters_order_id'), table_name='production_counters')
    op.drop_index(op.f('ix_production_counters_id'), table_name='production_counters')
    op.drop_index(op.f('ix_production_counters_equipment_id'), table_name='production_counters')
    op.drop_table('production_counters')
    op.drop_index(op.f('ix_lots_product_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_order_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_lot_number'), table_name='lots')
    op.drop_index(op.f('ix_lots_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_current_step_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_current_equipment_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_equipment_state_logs_started_at'), table_name='equipment_state_logs')
    op.drop_index(op.f('ix_equipment_state_logs_id'), table_name='equipment_state_logs')
    op.drop_index(op.f('ix_equipment_state_logs_equipment_id'), table_name='equipment_state_logs')
    op.drop_table('equipment_state_logs')
    op.drop_index(op.f('ix_data_definitions_step_id'), table_name='data_definitions')
    op.drop_index(op.f('ix_data_definitions_name'), table_name='data_definitions')
    op.drop_index(op.f('ix_data_definitions_id'), table_name='data_definitions')
    op.drop_index(op.f('ix_data_definitions_code'), table_name='data_definitions')
    op.drop_table('data_definitions')
    op.drop_index(op.f('ix_route_steps_work_cell_id'), table_name='route_steps')
    op.drop_index(op.f('ix_route_steps_route_id'), table_name='route_steps')
    op.drop_index(op.f('ix_route_steps_id'), table_name='route_steps')
    op.drop_table('route_steps')
    op.drop_index(op.f('ix_equipment_work_cell_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_code'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_work_cells_name'), table_name='work_cells')
    op.drop_index(op.f('ix_work_cells_line_id'), table_name='work_cells')
    op.drop_index(op.f('ix_work_cells_id'), table_name='work_cells')
    op.drop_index(op.f('ix_work_cells_code'), table_name='work_cells')
    op.drop_table('work_cells')
    op.drop_index(op.f('ix_production_orders_route_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_product_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_order_number'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_id'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_production_lines_name'), table_name='production_lines')
    op.drop_index(op.f('ix_production_lines_id'), table_name='production_lines')
    op.drop_index(op.f('ix_production_lines_code'), table_name='production_lines')
    op.drop_index(op.f('ix_production_lines_area_id'), table_name='production_lines')
    op.drop_table('production_lines')
    op.drop_index(op.f('ix_bom_items_id'), table_name='bom_items')
    op.drop_index(op.f('ix_bom_items_bom_id'), table_name='bom_items')
    op.drop_table('bom_items')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_process_routes_product_id'), table_name='process_routes')
    op.drop_index(op.f('ix_process_routes_name'), table_name='process_routes')
    op.drop_index(op.f('ix_process_routes_id'), table_name='process_routes')
    op.drop_table('process_routes')
    op.drop_index(op.f('ix_permissions_role_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_permission'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_material_lots_material_id'), table_name='material_lots')
    op.drop_index(op.f('ix_material_lots_lot_number'), table_name='material_lots')
    op.drop_index(op.f('ix_material_lots_id'), table_name='material_lots')
    op.drop_table('material_lots')
    op.drop_index(op.f('ix_idp_group_mappings_role_id'), table_name='idp_group_mappings')
    op.drop_index(op.f('ix_idp_group_mappings_idp_group'), table_name='idp_group_mappings')
    op.drop_index(op.f('ix_idp_group_mappings_id'), table_name='idp_group_mappings')
    op.drop_table('idp_group_mappings')
    op.drop_index(op.f('ix_bills_of_material_product_id'), table_name='bills_of_material')
    op.drop_index(op.f('ix_bills_of_material_id'), table_name='bills_of_material')
    op.drop_table('bills_of_material')
    op.drop_index(op.f('ix_areas_site_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_name'), table_name='areas')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_code'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_idp_subject'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_units_of_measure_uom_type'), table_name='units_of_measure')
    op.drop_index(op.f('ix_units_of_measure_symbol'), table_name='units_of_measure')
    op.drop_index(op.f('ix_units_of_measure_id'), table_name='units_of_measure')
    op.drop_table('units_of_measure')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_code'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_product_definitions_name'), table_name='product_definitions')
    op.drop_index(op.f('ix_product_definitions_id'), table_name='product_definitions')
    op.drop_index(op.f('ix_product_definitions_code'), table_name='product_definitions')
    op.drop_table('product_definitions')
    op.drop_index(op.f('ix_material_definitions_name'), table_name='material_definitions')
    op.drop_index(op.f('ix_material_definitions_id'), table_name='material_definitions')
    op.drop_index(op.f('ix_material_definitions_code'), table_name='material_definitions')
    op.drop_table('material_definitions')
    # ### end Alembic commands ###
