"""generic types uuid and json

Revision ID: ee4a56a35d22
Revises: a2b3c4d5e6f7
Create Date: 2026-04-08 08:49:53.249903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee4a56a35d22'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin_config', 'parameter_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='User-provided parameter values (filled during install)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('plugin_config', 'parameter_values',
               server_default=sa.text("'{}'"))
    op.alter_column('plugin_config', 'config_overrides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='Additional runtime config overrides (merged over manifest defaults)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('plugin_config', 'config_overrides',
               server_default=sa.text("'{}'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin_config', 'config_overrides',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Additional runtime config overrides (merged over manifest defaults)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('plugin_config', 'parameter_values',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='User-provided parameter values (filled during install)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###
