"""add_step_transitions_table

Revision ID: e386092bb59c
Revises: b2c3d4e5f6a8
Create Date: 2026-04-02 11:34:16.984798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e386092bb59c'
down_revision: Union[str, None] = 'b2c3d4e5f6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_transitions',
    sa.Column('from_step_id', sa.UUID(), nullable=False, comment='Source step this transition originates from'),
    sa.Column('to_step_id', sa.UUID(), nullable=False, comment='Target step this transition leads to'),
    sa.Column('condition', sa.String(length=20), nullable=False, comment="Condition: 'always', 'on_pass', 'on_fail', 'on_rework', 'disposition'"),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Default transition when multiple match. Exactly one per from_step should be default.'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Higher priority transitions are evaluated first (0 = lowest)'),
    sa.Column('label', sa.String(length=255), nullable=True, comment="Human-readable label for disposition choices (e.g. 'Return to rework', 'Scrap')"),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['from_step_id'], ['route_steps.id'], ),
    sa.ForeignKeyConstraint(['to_step_id'], ['route_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_transitions_from_step_id'), 'step_transitions', ['from_step_id'], unique=False)
    op.create_index(op.f('ix_step_transitions_id'), 'step_transitions', ['id'], unique=False)
    op.create_index(op.f('ix_step_transitions_to_step_id'), 'step_transitions', ['to_step_id'], unique=False)
    op.alter_column('reasons', 'oee_bucket',
               existing_type=sa.VARCHAR(length=30),
               comment='OEE loss bucket: downtime_planned, downtime_unplanned, uptime_non_value, etc.',
               existing_comment='OEE loss bucket: downtime_planned, downtime_unplanned, etc.',
               existing_nullable=False)
    op.alter_column('reasons', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the entity',
               existing_nullable=False)
    op.alter_column('reasons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the entity was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reasons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the entity was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reasons', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag. False means the entity is logically deleted.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_reasons_id'), 'reasons', ['id'], unique=False)
    op.alter_column('route_steps', 'step_type',
               existing_type=sa.VARCHAR(length=20),
               comment="Step type: 'production', 'inspection', 'rework', or 'mrb'",
               existing_comment="Step type: 'production', 'inspection', or 'rework'",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('route_steps', 'step_type',
               existing_type=sa.VARCHAR(length=20),
               comment="Step type: 'production', 'inspection', or 'rework'",
               existing_comment="Step type: 'production', 'inspection', 'rework', or 'mrb'",
               existing_nullable=False)
    op.drop_index(op.f('ix_reasons_id'), table_name='reasons')
    op.alter_column('reasons', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag. False means the entity is logically deleted.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('reasons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the entity was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reasons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the entity was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reasons', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the entity',
               existing_nullable=False)
    op.alter_column('reasons', 'oee_bucket',
               existing_type=sa.VARCHAR(length=30),
               comment='OEE loss bucket: downtime_planned, downtime_unplanned, etc.',
               existing_comment='OEE loss bucket: downtime_planned, downtime_unplanned, uptime_non_value, etc.',
               existing_nullable=False)
    op.drop_index(op.f('ix_step_transitions_to_step_id'), table_name='step_transitions')
    op.drop_index(op.f('ix_step_transitions_id'), table_name='step_transitions')
    op.drop_index(op.f('ix_step_transitions_from_step_id'), table_name='step_transitions')
    op.drop_table('step_transitions')
    # ### end Alembic commands ###
