"""add_work_schedule_module

Revision ID: f72c48a370e4
Revises: b2c3d4e5f6a7
Create Date: 2026-05-02 12:05:18.045937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f72c48a370e4'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_schedules',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Unique schedule name'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('created_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was created (UTC)'),
    sa.Column('updated_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was last updated (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_schedules_id'), 'work_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_work_schedules_name'), 'work_schedules', ['name'], unique=True)
    op.create_table('non_working_periods',
    sa.Column('work_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='Length of the non-working period in seconds'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('created_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was created (UTC)'),
    sa.Column('updated_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was last updated (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['work_schedule_id'], ['work_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_non_working_periods_id'), 'non_working_periods', ['id'], unique=False)
    op.create_index(op.f('ix_non_working_periods_work_schedule_id'), 'non_working_periods', ['work_schedule_id'], unique=False)
    op.create_table('work_rotations',
    sa.Column('work_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('created_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was created (UTC)'),
    sa.Column('updated_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was last updated (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['work_schedule_id'], ['work_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_rotations_id'), 'work_rotations', ['id'], unique=False)
    op.create_index(op.f('ix_work_rotations_work_schedule_id'), 'work_rotations', ['work_schedule_id'], unique=False)
    op.create_table('work_shifts',
    sa.Column('work_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False, comment='Time of day when shift starts'),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='Shift length in seconds (max 86400)'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('created_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was created (UTC)'),
    sa.Column('updated_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was last updated (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['work_schedule_id'], ['work_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_shifts_id'), 'work_shifts', ['id'], unique=False)
    op.create_index(op.f('ix_work_shifts_work_schedule_id'), 'work_shifts', ['work_schedule_id'], unique=False)
    op.create_table('rotation_segments',
    sa.Column('rotation_id', sa.Uuid(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('days_on', sa.Integer(), nullable=False),
    sa.Column('days_off', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='1-based position in the rotation'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('created_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was created (UTC)'),
    sa.Column('updated_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was last updated (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['rotation_id'], ['work_rotations.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['work_shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rotation_segments_id'), 'rotation_segments', ['id'], unique=False)
    op.create_index(op.f('ix_rotation_segments_rotation_id'), 'rotation_segments', ['rotation_id'], unique=False)
    op.create_index(op.f('ix_rotation_segments_shift_id'), 'rotation_segments', ['shift_id'], unique=False)
    op.create_table('shift_breaks',
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='Break length in seconds'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('created_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was created (UTC)'),
    sa.Column('updated_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was last updated (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['shift_id'], ['work_shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_breaks_id'), 'shift_breaks', ['id'], unique=False)
    op.create_index(op.f('ix_shift_breaks_shift_id'), 'shift_breaks', ['shift_id'], unique=False)
    op.create_table('work_teams',
    sa.Column('work_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('rotation_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rotation_start', sa.Date(), nullable=False, comment="The calendar date on which day-1 of this team's rotation falls"),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('created_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was created (UTC)'),
    sa.Column('updated_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was last updated (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['rotation_id'], ['work_rotations.id'], ),
    sa.ForeignKeyConstraint(['work_schedule_id'], ['work_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_teams_id'), 'work_teams', ['id'], unique=False)
    op.create_index(op.f('ix_work_teams_rotation_id'), 'work_teams', ['rotation_id'], unique=False)
    op.create_index(op.f('ix_work_teams_work_schedule_id'), 'work_teams', ['work_schedule_id'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.String(length=100), nullable=False, comment='External identifier, e.g. employee ID or badge number'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('created_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was created (UTC)'),
    sa.Column('updated_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was last updated (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['team_id'], ['work_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_table('team_member_exceptions',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('shift_start', sa.DateTime(timezone=True), nullable=False, comment='Start of the shift instance this exception applies to'),
    sa.Column('add_member_id', sa.Uuid(), nullable=True, comment='TeamMember to add for this shift instance'),
    sa.Column('remove_member_id', sa.Uuid(), nullable=True, comment='TeamMember to remove for this shift instance'),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('created_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was created (UTC)'),
    sa.Column('updated_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was last updated (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['add_member_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['remove_member_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['work_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_member_exceptions_id'), 'team_member_exceptions', ['id'], unique=False)
    op.create_index(op.f('ix_team_member_exceptions_team_id'), 'team_member_exceptions', ['team_id'], unique=False)
    op.alter_column('bom_items', 'uom_id',
               existing_type=sa.UUID(),
               comment='Unit of measure — FK to units_of_measure.id',
               existing_nullable=False)
    op.alter_column('data_definitions', 'uom_id',
               existing_type=sa.UUID(),
               comment='Unit of measure — FK to units_of_measure.id',
               existing_nullable=True)
    op.add_column('defect_codes', sa.Column('created_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was created (UTC)'))
    op.add_column('defect_codes', sa.Column('updated_at_utc', sa.DateTime(), nullable=True, comment='Timestamp when the entity was last updated (UTC)'))
    op.alter_column('defect_codes', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Short mnemonic used in APIs and reports (e.g. WIRE_BOND_OPEN)',
               existing_nullable=False)
    op.alter_column('defect_codes', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Human-readable defect name',
               existing_nullable=False)
    op.alter_column('defect_codes', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment='Grouping for Pareto charts (e.g. dimensional, electrical)',
               existing_nullable=True)
    op.alter_column('defect_codes', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the entity',
               existing_nullable=False)
    op.alter_column('defect_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Timestamp when the entity was created')
    op.alter_column('defect_codes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Timestamp when the entity was last updated')
    op.alter_column('defect_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag. False means the entity is logically deleted.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_defect_codes_id'), 'defect_codes', ['id'], unique=False)
    op.alter_column('equipment_materials', 'design_speed_uom_id',
               existing_type=sa.UUID(),
               comment='Rate UoM for design speed — FK to units_of_measure.id',
               existing_nullable=False)
    op.alter_column('equipment_materials', 'reject_uom_id',
               existing_type=sa.UUID(),
               comment='UoM for rejected / scrap material — FK to units_of_measure.id',
               existing_nullable=False)
    op.alter_column('lots', 'scrap_reason',
               existing_type=sa.TEXT(),
               comment='Free-text reason provided when lot was scrapped',
               existing_nullable=True)
    op.alter_column('lots', 'scrap_disposition',
               existing_type=sa.VARCHAR(length=50),
               comment='Disposition applied at scrap (e.g. rework, destroy, return)',
               existing_nullable=True)
    op.alter_column('lots', 'defect_code_id',
               existing_type=sa.UUID(),
               comment='Structured defect code from catalog — enables Pareto analysis',
               existing_nullable=True)
    op.alter_column('lots', 'scrapped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the lot was scrapped',
               existing_nullable=True)
    op.alter_column('lots', 'hold_reason',
               existing_type=sa.TEXT(),
               comment='Reason the lot was placed on hold',
               existing_nullable=True)
    op.alter_column('material_definitions', 'uom_id',
               existing_type=sa.UUID(),
               comment='Default unit of measure — FK to units_of_measure.id',
               existing_nullable=False)
    op.alter_column('product_definitions', 'uom_id',
               existing_type=sa.UUID(),
               comment='Unit of measure — FK to units_of_measure.id',
               existing_nullable=False)
    op.alter_column('segment_material_requirements', 'uom_id',
               existing_type=sa.UUID(),
               comment='Unit of measure — FK to units_of_measure.id',
               existing_nullable=False)
    op.alter_column('segment_parameters', 'uom_id',
               existing_type=sa.UUID(),
               comment='Unit of measure — FK to units_of_measure.id',
               existing_nullable=True)
    op.alter_column('segment_response_lots', 'result',
               existing_type=sa.VARCHAR(length=20),
               comment='Step result: pass, fail, rework (null if still in-process)',
               existing_nullable=True)
    op.alter_column('segment_response_lots', 'disposition',
               existing_type=sa.VARCHAR(length=100),
               comment='Operator-selected disposition label at step completion',
               existing_nullable=True)
    op.alter_column('segment_response_lots', 'failure_mode',
               existing_type=sa.VARCHAR(length=200),
               comment='Free-text failure mode description when result=fail',
               existing_nullable=True)
    op.alter_column('segment_response_lots', 'defect_code_id',
               existing_type=sa.UUID(),
               comment='Structured defect code — enables Pareto across steps',
               existing_nullable=True)
    op.alter_column('segment_response_lots', 'scrap_reason',
               existing_type=sa.TEXT(),
               comment='Scrap reason if the lot was scrapped at this step',
               existing_nullable=True)
    op.drop_index(op.f('ix_srl_defect_code_id'), table_name='segment_response_lots')
    op.create_index(op.f('ix_segment_response_lots_defect_code_id'), 'segment_response_lots', ['defect_code_id'], unique=False)
    op.alter_column('segment_response_units', 'disposition',
               existing_type=sa.VARCHAR(length=100),
               comment='Operator-selected disposition label at step completion',
               existing_nullable=True)
    op.alter_column('segment_response_units', 'failure_mode',
               existing_type=sa.VARCHAR(length=200),
               comment='Free-text failure mode description when result=fail',
               existing_nullable=True)
    op.alter_column('segment_response_units', 'defect_code_id',
               existing_type=sa.UUID(),
               comment='Structured defect code — enables Pareto across steps',
               existing_nullable=True)
    op.alter_column('segment_response_units', 'scrap_reason',
               existing_type=sa.TEXT(),
               comment='Scrap reason if the unit was scrapped at this step',
               existing_nullable=True)
    op.drop_index(op.f('ix_sru_defect_code_id'), table_name='segment_response_units')
    op.create_index(op.f('ix_segment_response_units_defect_code_id'), 'segment_response_units', ['defect_code_id'], unique=False)
    op.alter_column('units', 'scrap_reason',
               existing_type=sa.TEXT(),
               comment='Free-text reason provided when unit was scrapped',
               existing_nullable=True)
    op.alter_column('units', 'scrap_disposition',
               existing_type=sa.VARCHAR(length=50),
               comment='Disposition applied at scrap (e.g. rework, destroy, return)',
               existing_nullable=True)
    op.alter_column('units', 'defect_code_id',
               existing_type=sa.UUID(),
               comment='Structured defect code from catalog — enables Pareto analysis',
               existing_nullable=True)
    op.alter_column('units', 'scrapped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the unit was scrapped',
               existing_nullable=True)
    op.alter_column('units', 'hold_reason',
               existing_type=sa.TEXT(),
               comment='Reason the unit was placed on hold',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('units', 'hold_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Reason the unit was placed on hold',
               existing_nullable=True)
    op.alter_column('units', 'scrapped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the unit was scrapped',
               existing_nullable=True)
    op.alter_column('units', 'defect_code_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Structured defect code from catalog — enables Pareto analysis',
               existing_nullable=True)
    op.alter_column('units', 'scrap_disposition',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Disposition applied at scrap (e.g. rework, destroy, return)',
               existing_nullable=True)
    op.alter_column('units', 'scrap_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Free-text reason provided when unit was scrapped',
               existing_nullable=True)
    op.drop_index(op.f('ix_segment_response_units_defect_code_id'), table_name='segment_response_units')
    op.create_index(op.f('ix_sru_defect_code_id'), 'segment_response_units', ['defect_code_id'], unique=False)
    op.alter_column('segment_response_units', 'scrap_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Scrap reason if the unit was scrapped at this step',
               existing_nullable=True)
    op.alter_column('segment_response_units', 'defect_code_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Structured defect code — enables Pareto across steps',
               existing_nullable=True)
    op.alter_column('segment_response_units', 'failure_mode',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Free-text failure mode description when result=fail',
               existing_nullable=True)
    op.alter_column('segment_response_units', 'disposition',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Operator-selected disposition label at step completion',
               existing_nullable=True)
    op.drop_index(op.f('ix_segment_response_lots_defect_code_id'), table_name='segment_response_lots')
    op.create_index(op.f('ix_srl_defect_code_id'), 'segment_response_lots', ['defect_code_id'], unique=False)
    op.alter_column('segment_response_lots', 'scrap_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Scrap reason if the lot was scrapped at this step',
               existing_nullable=True)
    op.alter_column('segment_response_lots', 'defect_code_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Structured defect code — enables Pareto across steps',
               existing_nullable=True)
    op.alter_column('segment_response_lots', 'failure_mode',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Free-text failure mode description when result=fail',
               existing_nullable=True)
    op.alter_column('segment_response_lots', 'disposition',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Operator-selected disposition label at step completion',
               existing_nullable=True)
    op.alter_column('segment_response_lots', 'result',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Step result: pass, fail, rework (null if still in-process)',
               existing_nullable=True)
    op.alter_column('segment_parameters', 'uom_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unit of measure — FK to units_of_measure.id',
               existing_nullable=True)
    op.alter_column('segment_material_requirements', 'uom_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unit of measure — FK to units_of_measure.id',
               existing_nullable=False)
    op.alter_column('product_definitions', 'uom_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unit of measure — FK to units_of_measure.id',
               existing_nullable=False)
    op.alter_column('material_definitions', 'uom_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Default unit of measure — FK to units_of_measure.id',
               existing_nullable=False)
    op.alter_column('lots', 'hold_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Reason the lot was placed on hold',
               existing_nullable=True)
    op.alter_column('lots', 'scrapped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the lot was scrapped',
               existing_nullable=True)
    op.alter_column('lots', 'defect_code_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Structured defect code from catalog — enables Pareto analysis',
               existing_nullable=True)
    op.alter_column('lots', 'scrap_disposition',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Disposition applied at scrap (e.g. rework, destroy, return)',
               existing_nullable=True)
    op.alter_column('lots', 'scrap_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Free-text reason provided when lot was scrapped',
               existing_nullable=True)
    op.alter_column('equipment_materials', 'reject_uom_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UoM for rejected / scrap material — FK to units_of_measure.id',
               existing_nullable=False)
    op.alter_column('equipment_materials', 'design_speed_uom_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Rate UoM for design speed — FK to units_of_measure.id',
               existing_nullable=False)
    op.drop_index(op.f('ix_defect_codes_id'), table_name='defect_codes')
    op.alter_column('defect_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag. False means the entity is logically deleted.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('defect_codes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Timestamp when the entity was last updated')
    op.alter_column('defect_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Timestamp when the entity was created')
    op.alter_column('defect_codes', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the entity',
               existing_nullable=False)
    op.alter_column('defect_codes', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Grouping for Pareto charts (e.g. dimensional, electrical)',
               existing_nullable=True)
    op.alter_column('defect_codes', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Human-readable defect name',
               existing_nullable=False)
    op.alter_column('defect_codes', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Short mnemonic used in APIs and reports (e.g. WIRE_BOND_OPEN)',
               existing_nullable=False)
    op.drop_column('defect_codes', 'updated_at_utc')
    op.drop_column('defect_codes', 'created_at_utc')
    op.alter_column('data_definitions', 'uom_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unit of measure — FK to units_of_measure.id',
               existing_nullable=True)
    op.alter_column('bom_items', 'uom_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unit of measure — FK to units_of_measure.id',
               existing_nullable=False)
    op.drop_index(op.f('ix_team_member_exceptions_team_id'), table_name='team_member_exceptions')
    op.drop_index(op.f('ix_team_member_exceptions_id'), table_name='team_member_exceptions')
    op.drop_table('team_member_exceptions')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_work_teams_work_schedule_id'), table_name='work_teams')
    op.drop_index(op.f('ix_work_teams_rotation_id'), table_name='work_teams')
    op.drop_index(op.f('ix_work_teams_id'), table_name='work_teams')
    op.drop_table('work_teams')
    op.drop_index(op.f('ix_shift_breaks_shift_id'), table_name='shift_breaks')
    op.drop_index(op.f('ix_shift_breaks_id'), table_name='shift_breaks')
    op.drop_table('shift_breaks')
    op.drop_index(op.f('ix_rotation_segments_shift_id'), table_name='rotation_segments')
    op.drop_index(op.f('ix_rotation_segments_rotation_id'), table_name='rotation_segments')
    op.drop_index(op.f('ix_rotation_segments_id'), table_name='rotation_segments')
    op.drop_table('rotation_segments')
    op.drop_index(op.f('ix_work_shifts_work_schedule_id'), table_name='work_shifts')
    op.drop_index(op.f('ix_work_shifts_id'), table_name='work_shifts')
    op.drop_table('work_shifts')
    op.drop_index(op.f('ix_work_rotations_work_schedule_id'), table_name='work_rotations')
    op.drop_index(op.f('ix_work_rotations_id'), table_name='work_rotations')
    op.drop_table('work_rotations')
    op.drop_index(op.f('ix_non_working_periods_work_schedule_id'), table_name='non_working_periods')
    op.drop_index(op.f('ix_non_working_periods_id'), table_name='non_working_periods')
    op.drop_table('non_working_periods')
    op.drop_index(op.f('ix_work_schedules_name'), table_name='work_schedules')
    op.drop_index(op.f('ix_work_schedules_id'), table_name='work_schedules')
    op.drop_table('work_schedules')
    # ### end Alembic commands ###
