"""add Layer 4 tables and ERP outbound queue

Creates tables: erp_outbound_queue, equipment_state_logs, production_counters,
quality_tests, non_conformances, test_results.
Fixes work_center→work_cell index renames on equipment, route_steps, work_cells.

Revision ID: c6b762b32512
Revises: 4c0016b2fcbc
Create Date: 2026-03-13 11:41:58.816639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b762b32512'
down_revision: Union[str, None] = '4c0016b2fcbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_outbound_queue',
    sa.Column('report_type', sa.String(length=50), nullable=False, comment='Report type: completion | consumption | scrap | labor | downtime | quality_result'),
    sa.Column('payload', sa.Text(), nullable=False, comment='JSON-serialized report data'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Queue status: pending | sent | failed | retry'),
    sa.Column('attempts', sa.Integer(), nullable=False, comment='Number of send attempts so far'),
    sa.Column('max_attempts', sa.Integer(), nullable=False, comment='Maximum retry attempts before marking as failed'),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True, comment='Next retry timestamp (exponential backoff)'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Error message from last failed attempt'),
    sa.Column('erp_doc_number', sa.String(length=100), nullable=True, comment='ERP document number if successfully sent'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_outbound_queue_id'), 'erp_outbound_queue', ['id'], unique=False)
    op.create_table('equipment_state_logs',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('state_model', sa.String(length=50), nullable=False, comment="State model plugin ID (e.g. 'packml', 'semi_e10', 'oee_tpm')"),
    sa.Column('state', sa.String(length=50), nullable=False, comment="Plugin-specific state name (e.g. 'Execute', 'Idle')"),
    sa.Column('sub_state', sa.String(length=50), nullable=True, comment='Optional sub-state within the state'),
    sa.Column('dispatch_category', sa.String(length=30), nullable=False, comment='Canonical dispatch category: available, busy, unavailable_planned, unavailable_unplanned'),
    sa.Column('oee_bucket', sa.String(length=30), nullable=False, comment='OEE bucket: uptime_value_add, uptime_non_value, downtime_planned, downtime_unplanned, excluded'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='When this state began'),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True, comment='When this state ended (null = current state)'),
    sa.Column('reason_code', sa.String(length=50), nullable=True, comment='Optional reason code for the state change'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_state_logs_equipment_id'), 'equipment_state_logs', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_equipment_state_logs_id'), 'equipment_state_logs', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_state_logs_started_at'), 'equipment_state_logs', ['started_at'], unique=False)
    op.create_table('production_counters',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('shift_date', sa.Date(), nullable=False, comment='The calendar date of the shift'),
    sa.Column('good_count', sa.Integer(), nullable=False),
    sa.Column('reject_count', sa.Integer(), nullable=False),
    sa.Column('rework_count', sa.Integer(), nullable=False),
    sa.Column('ideal_cycle_time_sec', sa.Float(), nullable=True, comment='Ideal cycle time in seconds for this product/equipment combo'),
    sa.Column('actual_run_time_sec', sa.Float(), nullable=True, comment='Actual productive run time in seconds for the shift'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_counters_equipment_id'), 'production_counters', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_production_counters_id'), 'production_counters', ['id'], unique=False)
    op.create_index(op.f('ix_production_counters_order_id'), 'production_counters', ['order_id'], unique=False)
    op.create_index(op.f('ix_production_counters_shift_date'), 'production_counters', ['shift_date'], unique=False)
    op.create_table('quality_tests',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique test code'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('test_type', sa.String(length=20), nullable=False, comment='Test type: inline, offline, destructive'),
    sa.Column('step_id', sa.UUID(), nullable=True, comment='Optional route step where this test is performed'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='JSON describing test parameters, criteria, and tolerances'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['step_id'], ['route_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_tests_code'), 'quality_tests', ['code'], unique=True)
    op.create_index(op.f('ix_quality_tests_id'), 'quality_tests', ['id'], unique=False)
    op.create_index(op.f('ix_quality_tests_name'), 'quality_tests', ['name'], unique=False)
    op.create_index(op.f('ix_quality_tests_step_id'), 'quality_tests', ['step_id'], unique=False)
    op.create_table('non_conformances',
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True, comment='Route step where the non-conformance was detected'),
    sa.Column('nc_type', sa.String(length=20), nullable=False, comment='Non-conformance type: defect, out_of_spec, other'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed description of the non-conformance'),
    sa.Column('disposition', sa.String(length=20), nullable=True, comment='Disposition: rework, scrap, use_as_is, return (null until resolved)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Workflow status: open, investigating, resolved, closed'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['route_steps.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_non_conformances_id'), 'non_conformances', ['id'], unique=False)
    op.create_index(op.f('ix_non_conformances_lot_id'), 'non_conformances', ['lot_id'], unique=False)
    op.create_index(op.f('ix_non_conformances_step_id'), 'non_conformances', ['step_id'], unique=False)
    op.create_index(op.f('ix_non_conformances_unit_id'), 'non_conformances', ['unit_id'], unique=False)
    op.create_table('test_results',
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True, comment='Unit tested (null if lot-level test)'),
    sa.Column('lot_id', sa.UUID(), nullable=True, comment='Lot tested (null if unit-level test)'),
    sa.Column('result', sa.String(length=10), nullable=False, comment='Test result: pass, fail'),
    sa.Column('measured_values', sa.JSON(), nullable=True, comment='JSON of measured values (e.g. {"dimension_a": 10.5})'),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('equipment_id', sa.UUID(), nullable=True, comment='Test equipment used'),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=False, comment='When the test was performed'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['quality_tests.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_equipment_id'), 'test_results', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.create_index(op.f('ix_test_results_lot_id'), 'test_results', ['lot_id'], unique=False)
    op.create_index(op.f('ix_test_results_operator_id'), 'test_results', ['operator_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_id'), 'test_results', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_results_unit_id'), 'test_results', ['unit_id'], unique=False)
    op.drop_index(op.f('ix_equipment_work_center_id'), table_name='equipment')
    op.create_index(op.f('ix_equipment_work_cell_id'), 'equipment', ['work_cell_id'], unique=False)
    op.alter_column('route_steps', 'work_cell_id',
               existing_type=sa.UUID(),
               comment='Work cell where this step is performed (nullable for unassigned steps)',
               existing_comment='Work center where this step is performed (nullable for unassigned steps)',
               existing_nullable=True)
    op.drop_index(op.f('ix_route_steps_work_center_id'), table_name='route_steps')
    op.create_index(op.f('ix_route_steps_work_cell_id'), 'route_steps', ['work_cell_id'], unique=False)
    op.alter_column('work_cells', 'wc_type',
               existing_type=sa.VARCHAR(length=20),
               comment="Work cell type: 'manual' or 'automated'",
               existing_comment="Work center type: 'manual' or 'automated'",
               existing_nullable=False)
    op.drop_index(op.f('ix_work_centers_code'), table_name='work_cells')
    op.drop_index(op.f('ix_work_centers_id'), table_name='work_cells')
    op.drop_index(op.f('ix_work_centers_line_id'), table_name='work_cells')
    op.drop_index(op.f('ix_work_centers_name'), table_name='work_cells')
    op.create_index(op.f('ix_work_cells_code'), 'work_cells', ['code'], unique=True)
    op.create_index(op.f('ix_work_cells_id'), 'work_cells', ['id'], unique=False)
    op.create_index(op.f('ix_work_cells_line_id'), 'work_cells', ['line_id'], unique=False)
    op.create_index(op.f('ix_work_cells_name'), 'work_cells', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_cells_name'), table_name='work_cells')
    op.drop_index(op.f('ix_work_cells_line_id'), table_name='work_cells')
    op.drop_index(op.f('ix_work_cells_id'), table_name='work_cells')
    op.drop_index(op.f('ix_work_cells_code'), table_name='work_cells')
    op.create_index(op.f('ix_work_centers_name'), 'work_cells', ['name'], unique=False)
    op.create_index(op.f('ix_work_centers_line_id'), 'work_cells', ['line_id'], unique=False)
    op.create_index(op.f('ix_work_centers_id'), 'work_cells', ['id'], unique=False)
    op.create_index(op.f('ix_work_centers_code'), 'work_cells', ['code'], unique=True)
    op.alter_column('work_cells', 'wc_type',
               existing_type=sa.VARCHAR(length=20),
               comment="Work center type: 'manual' or 'automated'",
               existing_comment="Work cell type: 'manual' or 'automated'",
               existing_nullable=False)
    op.drop_index(op.f('ix_route_steps_work_cell_id'), table_name='route_steps')
    op.create_index(op.f('ix_route_steps_work_center_id'), 'route_steps', ['work_cell_id'], unique=False)
    op.alter_column('route_steps', 'work_cell_id',
               existing_type=sa.UUID(),
               comment='Work center where this step is performed (nullable for unassigned steps)',
               existing_comment='Work cell where this step is performed (nullable for unassigned steps)',
               existing_nullable=True)
    op.drop_index(op.f('ix_equipment_work_cell_id'), table_name='equipment')
    op.create_index(op.f('ix_equipment_work_center_id'), 'equipment', ['work_cell_id'], unique=False)
    op.drop_index(op.f('ix_test_results_unit_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_test_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_operator_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_lot_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_equipment_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_non_conformances_unit_id'), table_name='non_conformances')
    op.drop_index(op.f('ix_non_conformances_step_id'), table_name='non_conformances')
    op.drop_index(op.f('ix_non_conformances_lot_id'), table_name='non_conformances')
    op.drop_index(op.f('ix_non_conformances_id'), table_name='non_conformances')
    op.drop_table('non_conformances')
    op.drop_index(op.f('ix_quality_tests_step_id'), table_name='quality_tests')
    op.drop_index(op.f('ix_quality_tests_name'), table_name='quality_tests')
    op.drop_index(op.f('ix_quality_tests_id'), table_name='quality_tests')
    op.drop_index(op.f('ix_quality_tests_code'), table_name='quality_tests')
    op.drop_table('quality_tests')
    op.drop_index(op.f('ix_production_counters_shift_date'), table_name='production_counters')
    op.drop_index(op.f('ix_production_counters_order_id'), table_name='production_counters')
    op.drop_index(op.f('ix_production_counters_id'), table_name='production_counters')
    op.drop_index(op.f('ix_production_counters_equipment_id'), table_name='production_counters')
    op.drop_table('production_counters')
    op.drop_index(op.f('ix_equipment_state_logs_started_at'), table_name='equipment_state_logs')
    op.drop_index(op.f('ix_equipment_state_logs_id'), table_name='equipment_state_logs')
    op.drop_index(op.f('ix_equipment_state_logs_equipment_id'), table_name='equipment_state_logs')
    op.drop_table('equipment_state_logs')
    op.drop_index(op.f('ix_erp_outbound_queue_id'), table_name='erp_outbound_queue')
    op.drop_table('erp_outbound_queue')
    # ### end Alembic commands ###
