"""add_equipment_materials_junction

Revision ID: ba6f6fcc58bb
Revises: 93090f15e87b
Create Date: 2026-03-28 13:47:37.760156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6f6fcc58bb'
down_revision: Union[str, None] = '93090f15e87b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_materials',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('design_speed', sa.Float(), nullable=False, comment='Nameplate design speed for good produced material'),
    sa.Column('design_speed_uom', sa.String(length=20), nullable=False, comment='Rate UoM for design speed (e.g. EA/h)'),
    sa.Column('reject_uom', sa.String(length=20), nullable=False, comment='UoM for rejected / scrap material (e.g. EA, kg)'),
    sa.Column('target_oee', sa.Float(), nullable=False, comment='Target OEE percentage (0–100)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the entity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the entity was last updated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag. False means the entity is logically deleted.'),
    sa.ForeignKeyConstraint(['design_speed_uom'], ['units_of_measure.symbol'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material_definitions.id'], ),
    sa.ForeignKeyConstraint(['reject_uom'], ['units_of_measure.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_id', 'material_id', name='uq_equip_material')
    )
    op.create_index(op.f('ix_equipment_materials_equipment_id'), 'equipment_materials', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_equipment_materials_id'), 'equipment_materials', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_materials_material_id'), 'equipment_materials', ['material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_materials_material_id'), table_name='equipment_materials')
    op.drop_index(op.f('ix_equipment_materials_id'), table_name='equipment_materials')
    op.drop_index(op.f('ix_equipment_materials_equipment_id'), table_name='equipment_materials')
    op.drop_table('equipment_materials')
    # ### end Alembic commands ###
